### ISSUE TITLE
some names/labels for non-normal modal logic axioms

### ISSUE THREAD

**Issue by davfuenmayor** [TPTPWorld/NonClassicalLogicWebPages#19]
Additional more or less standard names for modal axioms in the non-normal world are:
(C)   |--  [.]A /\ [.]B -> [.](A /\ B)
(M)  |--  [.](A /\ B) -> [.]A
and the good old (K)  |-- [.](A -> B) -> ([.]A -> [.]B)

As for (C), we can also consider its right-to-left counterpart, say (C*)  |--  [.](A /\ B) -> [.]A /\ [.]B

In the non-normal world [.] and <.> are not always dual. So this axiom makes sense sometimes:
(Dual)  |-- [.]A <-> ~<.>~A
In which case we could also consider the duals of the axioms above, e.g.
(C-dual)  |-- <.>A \/ <.>B -> <.>(A \/ B)    and  (C*-dual)  |-- <.>(A \/ B) -> <.>A \/ <.>B

Some other conditions are stated as rules (using "global" consequence):
(RM)  from   |-- A -> B    infer   |-- [.]A -> [.]B
(RE)   from  |-- A <-> B   infer   |-- [.]A <-> [.]B
and the good old (Nec)  from  |-- A   infer  |-- [.]A

**Comment by geoffgeoffgeoff3** [comment]
Hi David,

I have added a new file LOG001_3.l with this. I think I am going to have
to split things up more finely, because it would not make sense for a 
non-normal modal logic problem to refer to all of the existing LOG001_1.l,
right? For example, LOG001_1.l always makes [.] and <.> dual, which might
not be the case in a non-normal setting.

Cheers,

Geoff

> Additional more or less standard names for modal axioms in the non-normal world are:
> (C)   |--  [.]A /\ [.]B -> [.](A /\ B)
> (M)  |--  [.](A /\ B) -> [.]A
> and the good old (K)  |-- [.](A -> B) -> ([.]A -> [.]B)
> 
> As for (C), we can also consider its right-to-left counterpart, say (C*)  |--  [.](A /\ B) -> [.]A /\ [.]B
> 
> In the non-normal world [.] and <.> are not always dual. So this axiom makes sense sometimes:
> (Dual)  |-- [.]A <-> ~<.>~A
> In which case we could also consider the duals of the axioms above, e.g.
> (C-dual)  |-- <.>A \/ <.>B -> <.>(A \/ B)    and  (C*-dual)  |-- <.>(A \/ B) -> <.>A \/ <.>B
> 
> Some other conditions are stated as rules (using "global" consequence):
> (RM)  from   |-- A -> B    infer   |-- [.]A -> [.]B
> (RE)   from  |-- A <-> B   infer   |-- [.]A <-> [.]B
> and the good old (Nec)  from  |-- A   infer  |-- [.]A
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/TPTPWorld/NonClassicalLogicWebPages/issues/19

-- 
Geoff Sutcliffe                           
http://www.cs.miami.edu/~geoff
"My cat" is not a float. Every string should learn to swim.
Despite the high cost of living, it's still surprisingly popular.

**Comment by davfuenmayor** [comment]
Actually, now that I think more carefully, it does make sense to always make [.] and <.> dual (also in non-normal settings). In those logics where this does not hold, [.] and <.> are actually two different modalities (i.e. they are bimodal)

**Comment by geoffgeoffgeoff3** [comment]
Hi David,

> Actually, now that I think more carefully, it does make sense to always make [.] and <.> dual (also in non-normal settings). In those logics where this does not hold, [.] and <.> are actually two different modalities (i.e. they are bimodal)

OK. I removed dual from LOG001_3

Geoff

-- 
Geoff Sutcliffe                           
http://www.cs.miami.edu/~geoff
"My cat" is not a float. Every string should learn to swim.
Despite the high cost of living, it's still surprisingly popular.

**Comment by davfuenmayor** [comment]
@geoffgeoffgeoff3 btw you can also remove "C_dual"

**Comment by geoffgeoffgeoff3** [comment]
Done. I have closed this, but reopen if I have missed any work.

**Comment by davfuenmayor** [comment]
A move these comments here from a previous message (which I have been editing relentlessly... a bad practice I see now ;)

I see some potential issues with the encoding of the inference rules (necessitation, RM, RE). I assume the symbol "-->" is intended as some sort of turnstile. This is only correct if "-->" is taken to correspond to global consequence. If "-->" is understood as local consequence then this is wrong (e.g. this would lead to "modal collapse" in the case of necessitation).

Last but not least: the literature on modal logics routinely interprets turnstiles as meaning *local* consequence (global consequence is rarely used, except implicitly for defining inference rules). It is also worth noticing that the deduction theorem (i.e. "swapping" turnstile & implication) holds for modal logics using local consequence but fails for global consequence. And to make things trickier, many people (maybe any ATP implementers?) still mix up concepts and terminology in this regard (cf. [this recent paper](https://www.jstor.org/stable/41682363) for a discussion.

So a possible solution that occurs to me:  what about just abstaining from formally encoding inference rules (Nec, RM, RE) as TPTP axioms? Would it suffice to add a  "natural-language disclaimer" describing what these rules mean and saying that it is up to ATP- implementers to sort out the details?
