### ISSUE TITLE
Formally encoding inference rules

### ISSUE THREAD

**Issue by davfuenmayor** [TPTPWorld/NonClassicalLogicWebPages#20]
(I move these comments here from a previous issue (which I have been editing relentlessly... a bad practice I see now ;)

I see some potential issues with the encoding of the inference rules (necessitation, RM, RE). I assume the symbol "-->" is intended as some sort of turnstile. This is only correct if "-->" is taken to correspond to global consequence. If "-->" is understood as local consequence then this is wrong (e.g. this would lead to "modal collapse" in the case of necessitation).

Moreover, the literature on modal logics routinely interprets turnstiles as meaning *local* consequence (global consequence is rarely used, except implicitly for defining inference rules). It is also worth noticing that the deduction theorem (i.e. "swapping" turnstile & implication) holds for modal logics using local consequence but fails for global consequence. And to make things trickier, many people (maybe any ATP implementers?) still mix up concepts and terminology in this regard (cf. [this recent paper](https://www.jstor.org/stable/41682363) for a discussion.

So a possible solution that occurs to me:  what about just abstaining from formally encoding inference rules (Nec, RM, RE) as TPTP axioms? Would it suffice to add a  "natural-language disclaimer" describing what these rules mean and saying that it is up to ATP- implementers to sort out the details?

**Comment by geoffgeoffgeoff3** [comment]
Hi,

> I see some potential issues with the encoding of the inference rules (necessitation, RM, RE). I assume the symbol "-->" is intended as some sort of turnstile. This is only correct if "-->" is taken to correspond to global consequence. If "-->" is understood as local consequence then this is wrong (e.g. this would lead to "modal collapse" in the case of necessitation).

Does that comment also apply to the normal modal logics that we are
focussed on right now? If so, maybe we can add a comment before all three
definitions ...

%----Here --> is global consequence.

?
 
> So a possible solution that occurs to me:  what about just abstaining from formally encoding inference rules (Nec, RM, RE) as TPTP axioms? Would it suffice to add a  "natural-language disclaimer" describing what these rules mean and saying that it is up to ATP- implementers to sort out the details?

Or both. If you can suggest some wording, or edit it in yourself, that
would be great!

Cheers,

Geoff
 
-- 
Geoff Sutcliffe                           
http://www.cs.miami.edu/~geoff
"My cat" is not a float. Every string should learn to swim.
Despite the high cost of living, it's still surprisingly popular.

**Comment by davfuenmayor** [comment]
Yes, my comment applies to the necessitation rule too.
Adding the comment you suggest could be an option.
The NL description of an inference rule of the form:
 |- A  
--------
 |- B 

reads as: if A is a theorem, then B is a theorem too (cf. necessitation)

**Comment by geoffgeoffgeoff3** [comment]
I have added comments that I think clarify this - take a look.

**Comment by davfuenmayor** [comment]
Yes, the comments are appropriate :)

**Comment by geoffgeoffgeoff3** [comment]
Then we are done. Closed!
